# MAXENT_CreateFieldList.py
#
#   Creates a CSV format list of fields to include in the MaxEnt analysis. Format of this
#   file is two fields: "Variable" and "Select" which are variable name and whether it should
#   be included in the analysis or not.
#
#   Initial fields are read in by the Correlations.csv file generated by the X.py script
#
# Inputs include:
#
#  Model output will be sent to the Outputs folder in the MaxEnt directory.
#
# Spring 2015
# John.Fay@duke.edu

import sys, os, arcpy, csv

# Input variables
swdFile = arcpy.GetParameterAsText(0)
fields = arcpy.GetParameterAsText(1)

# Output variables
fieldsCSV = arcpy.GetParameterAsText(2)

## ---Functions---
def msg(txt,type="message"):
    print txt
    if type == "message":
        arcpy.AddMessage(txt)
    elif type == "warning":
        arcpy.AddWarning(txt)
    elif type == "error":
        arcpy.AddError(txt)
        
## ---Processes---

# Get the first line of the SWD file
f = open(swdFile,'rt')
headers = csv.reader(f).next()
f.close()

# Remove nominal items
#headers.remove("Species")
#headers.remove("X")

#Make a list of keeper fields
keepList = fields.split(";")

# Initialize the output file
f = open(fieldsCSV,'wb')
writer = csv.writer(f)
writer.writerow(("Variable","Selected"))

for var in headers:
    if var in keepList:
        writer.writerow((var,"1"))
    else:
        writer.writerow((var,"0"))

f.close()




    
